/**
 * Admin Wrapper
 *
 * Imports plugin admin modules from the virtual module and passes them
 * to AdminApp via props. This ensures plugin components are bundled
 * together with the admin app and available via React context.
 */

import { AdminApp } from "@emdash-cms/admin";
// @ts-ignore - virtual module generated by integration
import { pluginAdmins } from "virtual:emdash/admin-registry";

export default function AdminWrapper() {
	return <AdminApp pluginAdmins={pluginAdmins} />;
}
